let car = "Mehran";
console.log("Is car == 'Mehran'? I predict true");
console.log(car == "Mehran");
console.log("Is car === 'Mehran'? I predict true");
console.log(car === "Mehran");
console.log("Is 5 =='5'? I predict true");
console.log(5 == "5");
console.log("Is 5 ==='5'? I predict false");
console.log(5 === "5");
console.log("Is 5-'2'== 5-2 ? I predict true");
console.log(5 - "2" == 5 - 2);
console.log("Is 5-'2'=== 5-2 ? I predict true");
console.log(5 - "2" === 5 - 2);
console.log("Is (10-2)%2 == (5-3)%2 ? I predict true");
console.log((10 - 2) % 2 == (5 - 3) % 2);
console.log("Is (10-3)%2 == (5-2)%2 ? I predict false");
console.log((10 - 3) % 2 == (5 - 3) % 2);
console.log("Is 10-3+4*1/2%2 == 10+4*1-3%2? I predict false");
console.log(10 - 3 + (((4 * 1) / 2) % 2) == 10 + 4 * 1 - (3 % 2));
console.log("Is Shehzad==shehzad? I predict false");
console.log("Shehzad" == "shehzad");
